# PROBLEM: MENENTUKAN HARGA TIKET BERDASARKAN USIA
# INPUTAN: USIA PENONTON
# PROSES: PERBANDINGAN JIKA A < 0 : USIA TIDAK VALID DAN JIKA A < 12TH : 30K DAN JIKA A > 12 : 50K
# OUTPUT: HARGA TIKET 

A = int(input('MASUKKAN USIA ANDA: '))
if A < 0 :
    print('USIA ANDA TIDAK VALID')
elif A < 12 and A > 0:
    print("HARGA TIKET ANDA: 30 RIBU")
else :
    print("HARGA TIKET ANDA: 60 RIBU")




